spring.application.name=sge

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/sge
spring.datasource.username=postgres
spring.datasource.password=password

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#JWT
jwt.secret=8f4c7a2d91e3b5f6c0a87d4e2f9b1c7356a8d0e4f2c19b7a3d6e8f0a5c2b4d91
jwt.expiration=864000000